### ISSUE TITLE
No Reminder Control?

### ISSUE THREAD

**Issue by jcrist1027** [SashaCX75/Amazfit#1]
Sorry, there is no where in app or that I could find here for author direct contact.  

Stock Amazfit watchface that comes on Zepp app displays next reminder event (bottom of watch face) I do not see any control in tjos watchface editor app for displaying next reminder event?  Can it be added?

[https://postimg.cc/R3pvr2Wn](url)

**Comment by SashaCX75** [comment]
There is no such possibility in the editor.
Is it a built-in watchface or is it installed from Zepp? If installed from Zepp, send the watchface bin file. I'll try to look at it and if it works out I'll add functionality.
